<?php
$this->layout('layouts/app', [
]);

$posts = $this->posts;
$pageNow = $posts->getCurrentPage();
$pagePrev = $pageNow == 1 ? '' : $pageNow - 1;
$pageCount = $posts->getPageCount();
$pageNext = $pageNow < $pageCount ? $pageNow + 1 : '';

?>
<?php $this->section('style');?>
<style>
    .main ul {
        list-style-type: none;
        padding: 0;
        padding-top: 4px;
    }
    .main ul li {
        position: relative;
        padding: 30px 0 30px;
        border-bottom: 1px solid #e6e6e6;
    }
    .main ul li:first-child {
        margin-top: -30px;
    }
    .main h2,
    .main h3 {
        letter-spacing: 1px;
        margin: 0;
        text-transform: uppercase;
    }
    .main h2 {
        font-size: 20px;
        letter-spacing: 1px;
        margin-left: 180px;
    }
    .main h2 a {
        color: #444;
    }
    .main h2 a:hover {
        color: #f33;
    }
    .main h3 {
        font-size: 13px;
        color: #999;
        position: absolute;
        left: 0;
        top: 33px;
    }
    @media screen and (max-width: 420px) {
        .main h2 {
            font-size: 16px;
            margin-left: 0;
        }
        .main h2 a:hover {
            color: #f66;
        }
        .main h3 {
            font-size: 11px;
            position: static;
            margin-bottom: 10px;
        }
        .main ul li {
            padding: 18px 0 20px;
        }
        .main ul li:first-child {
            margin-top: -35px;
        }
    }

</style>
<?php $this->replace();?>
<?php $this->section('main'); ?>
<section class="main">
    <div class="main">
        <ul>
            <?php foreach ($posts->getItems() as $post) { ?>
                <li>
                    <h3><?php echo $post->post_date;?></h3>
                    <h2><a href="<?php echo $this->routeGet('fetchPost', ['id' => $post->ID]); ?>"><?php echo $post->post_title ?></a></h2>
                </li>
            <?php } ?>
        </ul>
        <?php if ($pagePrev) { ?>
            <a id="newer" class="blog-nav" href="<?php echo $this->routeGet('listPost', [], ['page' => $pagePrev]);?>">&lt;&nbsp;NEWER</a>
        <?php } ?>
        <?php if ($pageNext) { ?>
            <a id="older" class="blog-nav" href="<?php echo $this->routeGet('listPost', [], ['page' => $pageNext]);?>">OLDER&nbsp;&gt;</a>
        <?php } ?>
    </div>
</section>
<?php $this->replace(); ?>
